// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYPc4cfwhEpMw7lo9Zk1EE4KFjNKMd9xw',
    appId: '1:941231212037:web:2b207c51383a77acaabe6c',
    messagingSenderId: '941231212037',
    projectId: 'my-travels-2d134',
    authDomain: 'my-travels-2d134.firebaseapp.com',
    storageBucket: 'my-travels-2d134.appspot.com',
    measurementId: 'G-SDYEJ7DDLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaYvPAgTPi9TbAZgoL4h7HSRn_NCF4Zjw',
    appId: '1:941231212037:android:9959f07553dcd4b9aabe6c',
    messagingSenderId: '941231212037',
    projectId: 'my-travels-2d134',
    storageBucket: 'my-travels-2d134.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuqTbeWtqbFRROZ1hh90zADtqobQ1SWCo',
    appId: '1:941231212037:ios:87cdadbab50b5fa2aabe6c',
    messagingSenderId: '941231212037',
    projectId: 'my-travels-2d134',
    storageBucket: 'my-travels-2d134.appspot.com',
    iosBundleId: 'com.example.dars8',
  );
}
